#!/usr/bin/env bash
# ============================================================
# KavachAI — Update Public URLs
#
# After deploying to Railway, this script updates all env files
# and config with the correct public URLs for each microservice.
#
# Usage:
#   ./scripts/update_public_urls.sh \
#     --worker  https://kavachai-worker-service-production.up.railway.app \
#     --policy  https://kavachai-policy-service-production.up.railway.app \
#     --trigger https://kavachai-trigger-engine-production.up.railway.app \
#     --claims  https://kavachai-claims-service-production.up.railway.app \
#     --payment https://kavachai-payment-service-production.up.railway.app \
#     --ml      https://kavachai-ml-service-production.up.railway.app
# ============================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC}  $1"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
fail()  { echo -e "${RED}[FAIL]${NC}  $1"; exit 1; }

# ── Parse arguments ──────────────────────────────────────────
WORKER_URL=""
POLICY_URL=""
TRIGGER_URL=""
CLAIMS_URL=""
PAYMENT_URL=""
ML_URL=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --worker)  WORKER_URL="$2";  shift 2;;
        --policy)  POLICY_URL="$2";  shift 2;;
        --trigger) TRIGGER_URL="$2"; shift 2;;
        --claims)  CLAIMS_URL="$2";  shift 2;;
        --payment) PAYMENT_URL="$2"; shift 2;;
        --ml)      ML_URL="$2";      shift 2;;
        *) fail "Unknown argument: $1";;
    esac
done

# Validate all URLs provided
for name in WORKER POLICY TRIGGER CLAIMS PAYMENT ML; do
    var_name="${name}_URL"
    if [ -z "${!var_name}" ]; then
        fail "Missing --${name,,} URL. All 6 service URLs are required."
    fi
done

info "Updating public URLs across the project..."

# ── 1. Update admin-dashboard/.env ────────────────────────────
ADMIN_ENV="admin-dashboard/.env"
info "Writing ${ADMIN_ENV}..."
cat > "${ADMIN_ENV}" << EOF
# KavachAI Admin Dashboard — Production Environment
# Generated by update_public_urls.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

VITE_WORKER_URL=${WORKER_URL}
VITE_POLICY_URL=${POLICY_URL}
VITE_TRIGGER_URL=${TRIGGER_URL}
VITE_CLAIMS_URL=${CLAIMS_URL}
VITE_PAYMENT_URL=${PAYMENT_URL}
VITE_ML_URL=${ML_URL}
VITE_DEMO_MODE=false
EOF
ok "Admin dashboard .env written"

# ── 2. Update vercel.json env block ──────────────────────────
VERCEL_JSON="admin-dashboard/vercel.json"
if [ -f "${VERCEL_JSON}" ]; then
    info "Updating ${VERCEL_JSON}..."
    # Use python for reliable JSON manipulation
    python3 -c "
import json, sys

with open('${VERCEL_JSON}', 'r') as f:
    data = json.load(f)

data['build'] = data.get('build', {})
data['build']['env'] = {
    'VITE_WORKER_URL': '${WORKER_URL}',
    'VITE_POLICY_URL': '${POLICY_URL}',
    'VITE_TRIGGER_URL': '${TRIGGER_URL}',
    'VITE_CLAIMS_URL': '${CLAIMS_URL}',
    'VITE_PAYMENT_URL': '${PAYMENT_URL}',
    'VITE_ML_URL': '${ML_URL}',
}

with open('${VERCEL_JSON}', 'w') as f:
    json.dump(data, f, indent=2)
    f.write('\n')
"
    ok "vercel.json updated"
else
    warn "vercel.json not found — skipping"
fi

# ── 3. Update PUBLIC_URLS.md ─────────────────────────────────
info "Writing PUBLIC_URLS.md..."
cat > "PUBLIC_URLS.md" << EOF
# KavachAI — Public Service URLs

> Generated on $(date -u +%Y-%m-%dT%H:%M:%SZ)

| Service | Public URL |
|---------|-----------|
| Worker Service | ${WORKER_URL} |
| Policy Service | ${POLICY_URL} |
| Trigger Engine | ${TRIGGER_URL} |
| Claims Service | ${CLAIMS_URL} |
| Payment Service | ${PAYMENT_URL} |
| ML Service | ${ML_URL} |

## Quick Health Check

\`\`\`bash
# Verify all services are reachable
for url in "${WORKER_URL}" "${POLICY_URL}" "${TRIGGER_URL}" "${CLAIMS_URL}" "${PAYMENT_URL}" "${ML_URL}"; do
  echo "\${url}/health → \$(curl -sf \${url}/health | python3 -c 'import sys,json; print(json.load(sys.stdin).get(\"status\",\"????\"))' 2>/dev/null || echo '❌ UNREACHABLE')"
done
\`\`\`

## Demo Endpoints (for judges)

1. **Worker Profile**: \`${WORKER_URL}/api/v1/workers/6fc7ae56-8cc2-4d32-b8cf-c21844a177ce\`
2. **Policy List**: \`${POLICY_URL}/api/v1/policies/worker/6fc7ae56-8cc2-4d32-b8cf-c21844a177ce\`
3. **Exclusions**: \`${POLICY_URL}/api/v1/policies/exclusions/reference\`
4. **Claims**: \`${CLAIMS_URL}/api/v1/claims?limit=10\`
5. **Payment Summary (BCR)**: \`${PAYMENT_URL}/api/v1/payments/summary\`
6. **ML Health (11 models)**: \`${ML_URL}/health\`
7. **Trigger Status**: \`${TRIGGER_URL}/api/v1/trigger/status\`
EOF
ok "PUBLIC_URLS.md written"

# ── 4. Update worker-app .env ────────────────────────────────
WORKER_APP_ENV="worker-app/.env"
info "Writing ${WORKER_APP_ENV}..."
cat > "${WORKER_APP_ENV}" << EOF
# KavachAI Worker App — Production Environment
# Generated by update_public_urls.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

EXPO_PUBLIC_WORKER_SERVICE=${WORKER_URL}
EXPO_PUBLIC_POLICY_SERVICE=${POLICY_URL}
EXPO_PUBLIC_TRIGGER_SERVICE=${TRIGGER_URL}
EXPO_PUBLIC_CLAIMS_SERVICE=${CLAIMS_URL}
EXPO_PUBLIC_PAYMENT_SERVICE=${PAYMENT_URL}
EXPO_PUBLIC_ML_SERVICE=${ML_URL}
EXPO_PUBLIC_WORKER_ID=6fc7ae56-8cc2-4d32-b8cf-c21844a177ce
EOF
ok "Worker app .env written"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ok "All public URLs updated successfully!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
info "Next steps:"
echo "  1. cd admin-dashboard && npm run build"
echo "  2. npx vercel --prod"
echo "  3. ./scripts/full_smoke_test.sh"
